// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptcffpiqkrpblonmkmba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Y2ZmcGlxa3JwYmxvbm1rbWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDU1MTQsImV4cCI6MjA3NDU4MTUxNH0.ru7UIImhJaZUs36lJvdMTU7HwpevJZEddhvems_UoC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});